module.exports = Object.freeze({
  WAITING_PLAYERS: "WAITING_PLAYERS",
  WAITING_ANSWERS: "WAITING_ANSWERS",
  PROCESSING_NEXT_QUESTION: "PROCESSING_NEXT_QUESTION",
  COMPUTING_RESULTS: "COMPUTING_RESULTS",
  GAME_OVER: "GAME_OVER"
});
